radarlegislativo/radarlegislativo/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from website.views import GrafoJson, TramitacoesFeed


urlpatterns = [
    url(r'^markdownx/', include('markdownx.urls')),
    url(r'^busca/', include('haystack.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^grafo.json', GrafoJson.as_view(), name='grafo-json'),
    url(r'^feed/todos.xml', TramitacoesFeed(), name='feed-todos'),
    url(r'^', include('website.urls', namespace='website')),
]

radarlegislativo/website/urls.py
# -*- coding: utf-8 -*-
# This file is part of Radar Legislativo
# Copyright © 2016 codingrights
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from django.conf.urls import url
from website.views import (Principal, DetalheProjeto, Agenda,
                           NovosPLs, Tramitabot, CenarioLegislativo, Sobre,
                           redirect_to_graphcommons)

urlpatterns = [
    url('^$', Principal.as_view(), name="principal"),
    url('^agenda/$', Agenda.as_view(), name="agenda"),
    url('^novos-pls/$', NovosPLs.as_view(), name="novos_pls"),
    url('^cenario-legislativo/$', CenarioLegislativo.as_view(),
        name="cenario_legislativo"),
    url('^grafo/$', redirect_to_graphcommons, name="grafo"),
    url('^sobre/$', Sobre.as_view(), name="sobre"),
    url('^tramitabot/$', Tramitabot.as_view(), name="tramitabot"),
    url('^projeto/(?P<pk>\d+)/$', DetalheProjeto.as_view(), name="projeto"),
]

radarlegislativo/agenda/models.py
# -*- coding: utf-8 -*-
# This file is part of Radar Legislativo
# Copyright © 2016 codingrights
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
from __future__ import unicode_literals

from django.db import models
from django.utils.encoding import python_2_unicode_compatible

from markdownx.models import MarkdownxField

from main.models import Projeto


@python_2_unicode_compatible
class Comissao(models.Model):
    origem = models.CharField(max_length=2, choices=Projeto.ORIGEM_CHOICES)
    nome = models.CharField(max_length=255)
    link = models.URLField(blank=True)

    class Meta:
        verbose_name = "comissão"
        verbose_name_plural = "comissões"

    def __str__(self):
        return u"{} - {}".format(self.nome, self.get_origem_display())


@python_2_unicode_compatible
class Evento(models.Model):
    data = models.DateField()
    link = models.URLField(blank=True)
    descricao = MarkdownxField()
    comissao = models.ForeignKey(Comissao)

    def __str__(self):
        return u"{} - {}".format(self.data, self.comissao)

radarlegislativo/main/models.py
#-*- coding: utf-8 -*-
# This file is part of Radar Legislativo
# Copyright © 2016 codingrights
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from __future__ import unicode_literals
import datetime

from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.text import slugify
from django.urls import reverse

from markdownx.models import MarkdownxField

URL_API_SENADO_MATERIA = u'http://legis.senado.leg.br/dadosabertos/materia/completa/{}'
URL_API_SENADO_MOVIMENTACOES = u'http://legis.senado.leg.br/dadosabertos/materia/movimentacoes/{}'
URL_WEB_SENADO = u'http://www25.senado.leg.br/web/atividade/materias/-/materia/{}'

URL_API_CAMARA = u'http://www.camara.gov.br/SitCamaraWS/Proposicoes.asmx?wsdl'
URL_WEB_CAMARA = u'http://www.camara.gov.br/proposicoesWeb/fichadetramitacao?idProposicao={}'

URL_APIV2_CAMARA = u'https://dadosabertos.camara.leg.br/api/v2/proposicoes/{}'
URL_APIV2_CAMARA_RELACIONADAS = URL_APIV2_CAMARA + u'/relacionadas'
URL_APIV2_CAMARA_AUTORES = URL_APIV2_CAMARA + u'/autores'


@python_2_unicode_compatible
class Tag(models.Model):
    nome = models.CharField('tag', max_length=256)
    slug = models.SlugField(max_length=20, unique=True)

    def __str__(self):
        return self.nome


@python_2_unicode_compatible
class Projeto(models.Model):
    CAMARA = "CA"
    SENADO = "SE"

    ORIGEM_CHOICES = (
        (CAMARA, "Câmara"),
        (SENADO, "Senado"),
    )

    VERDE = 1
    AMARELO = 2
    VERMELHO = 3

    IMPACTO_CHOICES = (
        (VERDE, '🙂️'),
        (AMARELO, "😐"),
        (VERMELHO, "🙁")
    )

    origem = models.CharField(max_length=2, choices=ORIGEM_CHOICES)
    id_site = models.IntegerField('id no site de origem')
    nome = models.CharField(max_length=255)
    tags = models.ManyToManyField(Tag)

    apresentacao = models.DateField()
    ementa = models.TextField()
    autoria = models.CharField(max_length=255)
    apensadas = models.TextField(blank=True)
    local = models.TextField(blank=True)

    html_original = models.TextField(blank=True)

    apelido = models.CharField(max_length=255, blank=True)
    importante = models.BooleanField(default=False)
    urgente = models.BooleanField(default=False)
    arquivado = models.BooleanField(default=False)
    impacto = models.IntegerField(choices=IMPACTO_CHOICES, default=AMARELO)
    informacoes_adicionais = MarkdownxField(blank=True)
    clippings = MarkdownxField(blank=True)
    pontos_principais = MarkdownxField(blank=True)
    texto_acao = models.TextField(blank=True)

    ultima_atualizacao = models.DateField(default=datetime.date.today)

    texto_acao.verbose_name = "texto de ação"

    class Meta:
        unique_together = (("origem", "id_site"),)
        ordering = ['-ultima_atualizacao']

    def tag_list(self):
        """
        Shows a list of tags for this project.

        We use this for the list_display in ProjetoAdmin, but it adds another
        (potentially big) query to that page. If it grows too slow, we can
        remove this (and not have a list of tags in the admin list_display).
        """
        return ', '.join(self.tags.values_list('nome',
            flat=True).order_by('nome'))

    @property
    def ultima_tramitacao(self):
        return self.tramitacao_set.latest()

    @property
    def ultimas_tramitacoes(self):
        return self.tramitacao_set.order_by('-data')

    @property
    def slug(self):
        return slugify(self.nome)

    @property
    def situacao(self):
        return "{} - {}".format(self.ultima_tramitacao.local, self.ultima_tramitacao.descricao)

    @property
    def link(self):
        if self.origem == self.SENADO:
            return URL_WEB_SENADO.format(self.id_site)
        elif self.origem == self.CAMARA:
            return URL_WEB_CAMARA.format(self.id_site)

    def get_absolute_url(self):
        return reverse("website:projeto", args=[self.pk])

    def __str__(self):
        return '{} - {}'.format(self.nome, self.get_origem_display())


@python_2_unicode_compatible
class Tramitacao(models.Model):
    id_site = models.CharField(max_length=255)
    data = models.DateField()
    projeto = models.ForeignKey(Projeto)
    local = models.CharField(max_length=255)
    descricao = models.TextField()

    class Meta:
        ordering = ["-data"]
        get_latest_by = "data"
        verbose_name_plural = "tramitações"

    def save(self, *args, **kwargs):
        result = super(Tramitacao, self).save(*args, **kwargs)
        self.projeto.ultima_atualizacao = self.data
        self.projeto.save()
        return result

    def get_absolute_url(self):
        return self.projeto.get_absolute_url()

    def __str__(self):
        return u'{} - {} - {}'.format(self.projeto, self.data, self.local)

radarlegislativo/tramitabot/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.utils.encoding import python_2_unicode_compatible


@python_2_unicode_compatible
class TramitabotUser(models.Model):
    username = models.CharField(max_length=255, blank=True)
    first_name = models.CharField(max_length=255, blank=True)
    last_name = models.CharField(max_length=255, blank=True)
    telegram_id = models.BigIntegerField()
    language_code = models.CharField(max_length=255, blank=True)
    has_blocked_us = models.BooleanField(default=False)

    def __str__(self):
        return "{} - {} {} - {}".format(self.username, self.first_name,
                self.last_name, self.telegram_id)

radarlegislativo/agenda/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render

# Create your views here.

radarlegislativo/tramitabot/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render

# Create your views here.

radarlegislativo/website/views.py
#  -*- coding: utf-8 -*-
# This file is part of Radar Legislativo
# Copyright © 2016 codingrights
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
from __future__ import unicode_literals

import datetime
import operator
from functools import reduce

from django.shortcuts import redirect
from django.contrib.syndication.views import Feed
from django.db.models import Q
from django.urls import reverse_lazy
from django.views.generic import DetailView, ListView, TemplateView, View
from django.http import JsonResponse, Http404

from haystack.generic_views import FacetedSearchView

from agenda.models import Comissao, Evento
from main.models import Projeto, Tramitacao
from website.models import WebsiteOptions

from graph.core import generate_graph
from search.forms import DefaultFullSearchForm
from website.forms import FilterForm, AgendaForm


class Principal(FacetedSearchView):
    model = Projeto
    template_name = "website/index.html"
    context_object_name = "projetos"
    paginate_by = 10
    form_class = DefaultFullSearchForm
    facet_fields = ["origem"]

    def get_ordering(self):
        ordem = self.request.GET.get("ordem")
        # Isso é um conjunto de if por que as ordenações não são
        # diretamente relacionadas aos campos do modelo
        if ordem == u'novos':
            return '-apresentacao'
        if ordem == u'urgentes':
            return '-urgente'
        if ordem == u'arquivados':
            return '-arquivado'
        else:
            return '-ultima_atualizacao'

    def get_queryset(self, *args, **kwargs):
        qs = super(Principal, self).get_queryset(*args, **kwargs)
        filter_form = FilterForm(self.request.GET)
        if filter_form.is_valid():
            origem = filter_form.cleaned_data['origem']
            if origem:
                qs = qs.filter(origem__in=origem)
            categorias = filter_form.cleaned_data['categoria']
            if categorias:
                query = reduce(
                    operator.and_,
                    (Q(categoria=cat) for cat in categorias)
                )
                qs = qs.filter(query)
            impacto = filter_form.cleaned_data['impacto']
            if impacto:
                qs = qs.filter(impacto__in=impacto)
            comissao = filter_form.cleaned_data['comissao']
            if comissao:
                nome_da_comissao = Comissao.objects.get(pk=comissao).nome
                qs = qs.filter(comissao=nome_da_comissao)
        return qs

    def get_context_data(self, *args, **kwargs):
        context = super(Principal, self).get_context_data(*args, **kwargs)
        context["filter_form"] = FilterForm(self.request.GET)
        return context


class TramitacoesFeed(Feed):
    title = ("Projetos de Lei — Projetos de Lei que são relevantes "
             "para a privacidade, liberdade de expressão, acesso, "
             "inovação e questões de gênero no meio digital")

    description = "Feed unificado dos PL's na página radarlegislativo.org"

    def link(self):
        return "https://radarlegislativo.org/{}".format(
            reverse_lazy("feed-todos")
        )

    def items(self):
        return Tramitacao.objects.order_by("-data")[:25]

    def item_title(self, item):
        return "{} - {}".format(item.projeto.nome, item.local)

    def item_description(self, item):
        return item.descricao

    def item_pubdate(self, item):
        return datetime.datetime.combine(item.data, datetime.time())

    def item_guid(self, item):
        return "{}-{}".format(item.get_absolute_url(), item.id)

    item_guid_is_permalink = True


class DetalheProjeto(DetailView):
    model = Projeto
    template_name = "website/projeto.html"


class Agenda(ListView):
    model = Evento
    template_name = "website/agenda.html"
    _date = None
    _origem = None

    @property
    def date(self):
        if self._date is None:
            self.validate_form()
        return self._date

    @property
    def semanas_proximas(self):
        inicios = [
            self.dias_da_semana[0] + datetime.timedelta(days=n * 7)
            for n in range(-3, 4)
        ]
        semanas = []
        for dia in inicios:
            semanas.append((dia, (dia + datetime.timedelta(days=6))))
        return semanas

    @property
    def dias_da_semana(self):
        inicio_da_semana = self.date - datetime.timedelta(self.date.weekday())
        return [
            inicio_da_semana + datetime.timedelta(days=n) for n in range(7)
        ]

    def validate_form(self):
        date = datetime.date.today()
        if self.request.GET.get('data'):
            self.form = AgendaForm(self.request.GET)
            if self.form.is_valid():
                date = self.form.cleaned_data['data']
                self._origem = self.form.cleaned_data['origem']
        else:
            self.form = AgendaForm()
        self._date = date

    def get_queryset(self):
        qs = (Evento.objects.filter(data__in=self.dias_da_semana)
                            .order_by('data'))
        if self._origem and self._origem != AgendaForm.origem_default:
            qs = qs.filter(comissao__origem=self._origem)
        return qs

    def get_context_data(self, **kwargs):
        context = super(Agenda, self).get_context_data(**kwargs)

        hoje = datetime.date.today()

        context['data'] = self.date
        context['hoje'] = hoje
        context['semanas_proximas'] = self.semanas_proximas
        context['dias_da_semana'] = self.dias_da_semana
        context['inicio_da_semana_atual'] = (
            hoje - datetime.timedelta(hoje.weekday()))
        context['form'] = self.form

        return context


class Tramitabot(TemplateView):
    template_name = "website/tramitabot.html"


class CenarioLegislativo(TemplateView):
    template_name = "website/cenario_legislativo.html"


class NovosPLs(TemplateView):
    template_name = "website/novos_pls.html"


class Sobre(TemplateView):
    template_name = "website/sobre.html"


class GrafoJson(View):
    def get(self, request):
        return JsonResponse(generate_graph())


def redirect_to_graphcommons(request):
    options = WebsiteOptions.objects.first()
    if options is None:
        raise Http404
    return redirect(options.graph_url)

radarlegislativo/website/templates/website/agenda.html
{% extends "website/base.html" %}
{% load static %}
{% load website_tags %}

{% block extra_title %}| Agenda da semana{% endblock %}

{% block body_class %}class="pagina-agenda"{% endblock %}

{% block extra_head %}
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css">
{% endblock %}

{% block header %}
  <!-- HEADER -->
  <div class="main-page-header container-fluid text-center">
    <h1>Agenda da semana</h1>
    <p>Acompanhamento semanal das prioridades no Congresso</p>
    <img class="robo" src="{% static 'img/cabecalho-robo.jpg' %}" alt="" />
  </div>
  <!-- HEADER -->
{% endblock %}

{% block conteudo %}
  <div class="filtros-agenda container-fluid text-center">
    <form id="filtros" method="get">
      {{ form.origem }}
      {{ form.data }}
    </form>
  </div>

  <div class="datas-agenda container-fluid text-center">
    <div class="row table-row-sm item-divider">
    {% for inicio, fim in semanas_proximas %}
      {% if forloop.first %}
        <div class="col-sm-1">
          <a href="{% change_url_parameter request 'data' inicio|date:'d/m/Y' %}">
            <span class="navegacao glyphicon glyphicon-menu-left" aria-hidden="true"></span>
          </a>
        </div>
      {% elif forloop.last %}
        <div class="col-sm-1">
          <a href="{% change_url_parameter request 'data' inicio|date:'d/m/Y' %}">
            <span class="navegacao glyphicon glyphicon-menu-right" aria-hidden="true"></span>
          </a>
	</div>
      {% else %}
        <div class="col-sm-2{% if inicio in dias_da_semana %} active{% endif %}">
          <a href="{% change_url_parameter request 'data' inicio|date:'d/m/Y' %}">
            <p class="agenda-data-mes">{{ inicio|date:"d/m" }} - {{ fim|date:"d/m" }}</p>
            {% if inicio == inicio_da_semana_atual %}
              <p class="agenda-data-hoje">esta semana</p>
            {% endif %}
          </a>
        </div>
      {% endif %}
    {% endfor %}
    </div>
  </div>

  <div class="conteudo-principal">
    <div class="container">
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
	  {% for evento in object_list %}

	  {% ifchanged evento.data %}
	    {% if not forloop.first %}<div class="divider-horizontal"></div>{% endif %}
	    <h2>{{ evento.data }}</h2>
	  {% endifchanged %}
          <h2>{{ evento.comissao }}</h2>

          <p>{{ evento.descricao|safe|markdown_text }}</p>

	  {% if not forloop.last %}
	  {% endif %}
	{% empty %}
	  <p>Não existem eventos prioritários agendados para essa semana.</p>
	{% endfor %}
      </div>
    </div>
  </div>

  <div class="divider-horizontal"></div>
{% endblock %}
{% block scripts_extra %}
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
  <script src="{% static 'js/forms.js' %}"></script>
  <script src="{% static 'js/datepicker-pt-BR.js' %}"></script>
  <script type="text/javascript">
    $(function() {
      $("#datepicker").datepicker({
        beforeShowDay: function(date){
          var day = date.getDay();
          return [day >= 1 && day <= 5, ""];
        }
      });
    });
  </script>
{% endblock %}

radarlegislativo/website/templates/website/base.html
{% load static %}
{% load website_tags %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Radar{% block titulo_extra %}{% endblock %}</title>
  <link rel="stylesheet" href="{% static 'styles/radar.css' %}">
  {% block extra_head %}{% endblock %}
</head>

<body {% block body_class %}{% endblock %}>
  {% block alerta %}{% endblock %}
  {% block menu_principal %}
  <!-- MENU PRINCIPAL -->
  <nav id="main_navbar" class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Abrir/fechar menu</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="{% url 'website:principal' %}">
          <img src="{% static 'img/antena-robo.svg' %}" alt="" />
          Radar
        </a>
      </div>

      <div class="collapse navbar-collapse navbar-right" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav divider">
          <li class="active"><a href="{% url 'website:principal' %}">Projetos de lei</a></li>
          <li><a href="{% url 'website:agenda' %}">Agenda da semana</a></li>
	  {% comment %}
          <li><a href="{% url 'website:novos_pls' %}">Novos PLs</a></li>
	  {% endcomment %}
          <li><a href="{% url 'website:cenario_legislativo' %}">Cenário legislativo</a></li>
          <li><a href="{% url 'website:sobre' %}">Sobre</a></li>
        </ul>
        <ul class="nav navbar-nav">
          <li role="separator" class="divider"></li>
          <li><a href="{% website_options 'graph_url' %}">Grafo de PLS</a></li>
          <li><a href="{% url 'website:tramitabot' %}">Tramitabot</a></li>
        </ul>
      </div>
    </div>
  </nav>
  <!-- MENU PRINCIPAL -->
  {% endblock %}

  {% block header %}
  <!-- HEADER -->
  <div class="main-page-header container-fluid text-center">
    <h1>Radar legislativo</h1>
    <p>acesso · gênero · liberdade de expressão · privacidade · inovação · direito do consumidor</p>
    <img class="robo" src="{% static 'img/cabecalho-robo.jpg' %}" alt="" />
  </div>
  <!-- HEADER -->
  {% endblock %}

  {% block conteudo %}

  {% endblock conteudo %}

  {% block rodape %}
  <!-- RODAPE -->
  <div class="rodape container-fluid">
    <div class="navegacao container">
      <div class="col-sm-4">
        <h6><strong>Radar.</strong> Tudo sobre leis e direitos humanos no meio digital.</h6>
        <ul class="nav">
          <li><a href="{% url 'website:agenda' %}">agenda da semana</a></li>
          <li><a href="{% url 'website:principal' %}">projetos de lei</a></li>
          <li><a href="{% url 'website:novos_pls' %}">novos PLs</a></li>
          <li><a href="{% url 'website:cenario_legislativo' %}">cenário legislativo</a></li>
          <li><a href="{% website_options 'graph_url' %}">grafo de pls</a></li>
          <li><a href="{% url 'website:tramitabot' %}">tramitabot</a></li>
          <li><a href="{% url 'website:sobre' %}">sobre</a></li>
        </ul>
      </div>
      <div class="col-sm-4">
        <h6>categorias</h6>
        <ul class="nav">
          <li><a href="{% link_filtro 'genero' %}">gênero</a></li>
          <li><a href="{% link_filtro 'acesso' %}">acesso</a></li>
          <li><a href="{% link_filtro 'inov' %}">inovação</a></li>
          <li><a href="{% link_filtro 'priv' %}">privacidade</a></li>
          <li><a href="{% link_filtro 'libex' %}">liberdade de expressão</a></li>
        </ul>
      </div>
      <div class="col-sm-4">
        <h6>Um projeto mantido pela  Coding Rights</h6>
        <p><a href="https://twitter.com/codingrights">@codingrights</a></p>
        <p><a href="https://antivigilancia.org/pt/boletim/">Assine o nosso boletim</a></p>
        <a href="https://www.codingrights.org"><img src="{% static 'img/logoCR.svg' %}" alt="Coding Rights logo" /></a>
      </div>
    </div>

    <div class="licenca row">
      <p>Este projeto está licenciado com uma Licença Creative Commons 4.0 CompartilhaIgual.</p>
      <p>Código aberto disponível no <a href="https://gitlab.com/codingrights"><img class="logo" src="{% static 'img/logo-gitlab.svg' %}" alt="" /> Gitlab</a></p>
    </div>
  </div>
  <!-- RODAPE -->
  {% endblock %}

  <!-- SCRIPTS -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>
  {% website_options "tracking_code" %}
  {% block scripts_extra %}
  {% endblock %}
  <!-- SCRIPTS -->
</body>
</html>

radarlegislativo/website/templates/website/cenario_legislativo.html
{% extends "website/pagina_estatica.html" %}
{% load static %}

{% block titulo_extra %} | Entenda o Legislativo {% endblock %}

{% block head_title %}Entenda o Legislativo{% endblock %}

{% block conteudo %}
  <div class="conteudo-principal container">
    <div class="row">
      <div class="col-md-12">
         <picture>
           <source media="(min-width: 1024px)" srcset="{% static 'img/entenda-legislativo.png' %}">
                 <img src="{% static 'img/entenda-legislativo-pequeno.png' %}" class="img-responsive" alt="Infográfico: Entenda o Legislativo">
         </picture>
	 <p>Infográfico por Daniel Roda e Kimberly Anastácio</p>
      </div>
    </div>
  </div>

  {% block conteudo_extra %}
  <br />
  <div class="divider-horizontal"></div>
  {% endblock %}

{% endblock conteudo %}

radarlegislativo/website/templates/website/checkbox_select_multiple.html
{% load static %}
{% load website_tags %}
{% with id=widget.attrs.id %}
  {% for group, options, index in widget.optgroups %}
    {% if group %}{{ group }}{% endif %}
    {% for option in options %}
      {% with widget=option %}
        <label{% if widget.attrs.id %} for="{{ widget.attrs.id }}"{% endif %} class="btn btn-default{% if widget.attrs.checked %} active{% endif %}" {% if widget.name == "impacto" %}data-toggle="tooltip" title="{% get_title_from_label widget.label %}"{% endif %}>
          {% include "django/forms/widgets/input.html" %}
		
		{% if widget.name == "categoria" %}

			{% if widget.label == 'acesso' %}
			<img src={% static "img/icone-acesso.svg" %} width="25" width="35" alt="ícone de acesso" />
	    {% elif widget.label == 'priv' %}
			<img src={% static "img/icone-priv.svg" %} width="25" width="35" alt="ícone de privacidade" />
	    {% elif widget.label == 'libex' %}
			<img src={% static "img/icone-libex.svg" %} width="25" width="35" alt="ícone de liberdade de expressão" />
			{% elif widget.label == 'genero' %}
			<img src={% static "img/icone-genero.svg" %} width="25" width="35" alt="ícone de questões de gênero" />
			{% elif widget.label == 'inov' %}
				<img src="{% static 'img/icons/inov-icon.svg' %}" />
			{% endif %}

		{% endif %}

	  {% if widget.name == "impacto" %}
	    {% if widget.label == '🙂️' %}
	      <img src="{% static 'img/icons/face-happy-icon.svg' %}" />
	    {% elif widget.label == '😐' %}
	      <img src="{% static 'img/icons/face-medium-icon.svg' %}" />
	    {% elif widget.label == '🙁' %}
	      <img src="{% static 'img/icons/face-unhappy-icon.svg' %}" />
	    {% endif %}
	  {% else %}
	    {{ widget.label }}
	  {% endif %}
	</label>
      {% endwith %}
    {% endfor %}
  {% endfor %}
{% endwith %}